package com.github.lmoraes7.tcc.uva.recruitment.selection.domain.model.constants;

public enum Functionality {
    FUNC_CREATE_STEP,
    FUNC_CREATE_QUESTION,
    FUNC_CREATE_SELECTIVE_PROCESS,
    FUNC_CLOSE_SELECTIVE_PROCESS,
    FUNC_CREATE_FEEDBACK,
    FUNC_RELEASE_STEP,
    FUNC_CONSULT_STEP_ANSWERS,
    FUNC_CONSULT_STEP,
    FUNC_REDEFINE_PASSWORD,
    FUNC_CREATE_CANDIDACY,
    FUNC_CONSULT_ALL_CANDIDACY,
    FUNC_CONSULT_CANDIDACY,
    FUNC_CLOSE_CANDIDACY,
    FUNC_EXEC_STEP,
    FUNC_CREATE_EMPLOYEE,
    FUNC_CREATE_PROFILE;
}
